### ISSUE TITLE
华为选择图片的时候会显示.downloading拓展名的文件

### ISSUE THREAD

**Issue by kmlidc** [DmcSDK/MediaPickerPoject#16]
华为 Honor 安卓8.0.0系统 只选择图片的时候 .downloading 拓展名文件也出来了

**Comment by DmcSDK** [comment]
是返回的参数的path属性吗？或是界面上的显示？如果是界面麻烦方便的话截图给我看看。

**Comment by kmlidc** [comment]
今天拿同一台手机试了下没有这个问题了，昨天的问题是进入图片选择列表的时候 .downloading 也加载出来了并且可以选择 但显示的是黑色 选中之后回调出来的路径拓展名是.downloading

**Comment by DmcSDK** [comment]
好的谢谢，感觉是系统或第三方APP把.downloading的文件 放进了media 数据库，百度了一下这种文件应该是不能看也不能播放的。

**Comment by GitJoBo** [comment]
这个问题修复了吗？
