### ISSUE TITLE
显示问题 还有我下载不下来，

### ISSUE THREAD

**Issue by ousq** [DmcSDK/MediaPickerPoject#22]
![image](https://user-images.githubusercontent.com/18591884/51423710-f6563a00-1bfe-11e9-8d76-edcfb20cb1a0.png)

 我是没有图片先拍照 在进入选择 怎么默认有1了

**Comment by DmcSDK** [comment]
@ousq 
应该是你把拍照的照片数组放到defaultSelect了。
ArrayList<Media> defaultSelect = select;//可以设置默认选中的照片，比如把select刚刚选择的list设置成默认的。
        intent.putExtra(PickerConfig.DEFAULT_SELECTED_LIST,defaultSelect); //可以设置默认选中的照片(非必填参数)

**Comment by ousq** [comment]
我下载 demo 操作的

**Comment by ousq** [comment]
还有 我用as 下载要出错

**Comment by DmcSDK** [comment]
@ousq 那可能的确是个未知BUG，能描述下你的机器是什么系统版本是什么吗？或者加下我QQ：3451927565，或者留下您的QQ帮忙解决一下这个未知问题。
