### ISSUE TITLE
根本就用不了

### ISSUE THREAD

**Issue by nathan-zxx** [DmcSDK/MediaPickerPoject#23]
java.lang.NoSuchMethodError: No virtual method into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/Target; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in /data/app/com.hyphenate.chatuidemo-2/split_lib_dependencies_apk.apk:classes28.dex)

**Comment by DmcSDK** [comment]
@nathan-zxx  这似乎是个很常见的问题，我的这个库会引用依赖glide 4.0.0版本，同时似乎你的项目也引用了一份glide，而且版本也许不一致，两个glide有同一个方法，不知道运行所以哪一个造成运行出错。
