### ISSUE TITLE
Android API 33 no files visible

### ISSUE THREAD

**Issue by itbeyond** [DmcSDK/MediaPickerPoject#28]
As per comments in cordova-media-dmcsdk under API 33 no files and shown in the picker.

**Comment by jonmaim** [comment]
I'm having the same issue.

**Comment by bazuka5801** [comment]
> I'm having the same issue.

+1

**Comment by bazuka5801** [comment]
@jonmaim @itbeyond I fixed it! https://github.com/bazuka5801/MediaPickerPoject/commit/35d2e25b5e9e60776a168c51534dbb6b11e2e82e
